---
################################################################################
# This cloudstackagent.yml is used for deploying cloudstack agent node specified.
# It will:
# 1. Setup the NTP Server
# 2. Install Cloudstack Agent 
# 

########################### 1. Set the NTP Server ##################################
- hosts: csagent
  sudo: yes
  remote_user: root
  roles:
    - role: ansible-role-ntp
      ntp_config_server: [2.ubuntu.pool.ntp.org, 1.ubuntu.pool.ntp.org, 3.cn.pool.ntp.org]

########################### 2. Install Cloudstack Agent ##########################################
- hosts: csagent
  sudo: yes
  remote_user: root

  tasks:

    - name: Configure CloudStack Repo
      template: src=templates/cloudstack46.repo.j2 dest=/etc/yum.repos.d/cloudstack46.repo mode=0644

    - name: Re-generate the repository cache
      shell: yum clean all && yum makecache

###########################  Install cloudstack Agent ##################################
- hosts: csagent
  sudo: yes
  remote_user: root

  tasks:

    - name: Install CloudStack Agent
      yum: name=cloudstack-agent state=present

    - name: Configure the qemu.conf
      shell: sed -i 's/#vnc_listen = "0.0.0.0"/vnc_listen = "0.0.0.0"/g' /etc/libvirt/qemu.conf

    - name: Configure the libvirtd.conf
      shell: sed -i 's/#listen_tls = 0/listen_tls = 0/g' /etc/libvirt/libvirtd.conf && sed -i 's/#listen_tcp = 1/listen_tcp = 1/g' /etc/libvirt/libvirtd.conf && sed -i 's/#tcp_port = "16509"/tcp_port = "16509"/g' /etc/libvirt/libvirtd.conf && sed -i 's/#auth_tcp = "sasl"/auth_tcp = "none"/g' /etc/libvirt/libvirtd.conf && sed -i 's/#mdns_adv = 1/mdns_adv = 0/g' /etc/libvirt/libvirtd.conf

    - name: Configure the sysconfig libvirtd.conf
      shell: sed -i 's/#LIBVIRTD_ARGS="--listen"/LIBVIRTD_ARGS="--listen"/g' /etc/sysconfig/libvirtd 

    - name: Restart the libvirtd
      service: name=libvirtd state=restarted

